apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- quay-push-secret.yaml
- buildconfig.yaml

labels:
- pairs:
    app.kubernetes.io/component: builds
  includeSelectors: false
