apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- network-policies.yaml

labels:
- pairs:
    app.kubernetes.io/component: networking
  includeSelectors: false
