apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- llm-inference
- storage
- networking
- monitoring
- rl-training
- evaluator
- builds

labels:
- pairs:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false
