apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zelda-rl

resources:
- ../../base

patches:
- path: patches/llm-replicas-vision.yaml
- path: patches/llm-replicas-puzzle.yaml
- path: patches/llm-replicas-text.yaml
- path: patches/training-scale.yaml
