apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zelda-rl

resources:
- ../../base
- machinesets/llm-inference-machineset.yaml
- machinesets/pyboy-training-machineset.yaml

patches:
- path: patches/llm-replicas.yaml
- path: patches/training-scale.yaml
