apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zelda-rl-dev

resources:
- ../../base

patches:
- path: patches/llm-replicas.yaml
- path: patches/training-scale.yaml
- path: patches/minio-ephemeral.yaml

# Override namespace for dev
namePrefix: ""
