apiVersion: apps/v1
kind: Deployment
metadata:
  name: zelda-map-viz
  labels:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/component: visualization
    app.kubernetes.io/name: zelda-map-viz
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zelda-map-viz
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: zelda-rl
        app.kubernetes.io/component: visualization
        app.kubernetes.io/name: zelda-map-viz
    spec:
      containers:
      - name: map-viz
        image: quay.io/cnuland/zelda-map-viz:latest
        imagePullPolicy: Always
        ports:
        - name: http-ws
          containerPort: 3344
          protocol: TCP
        env:
        - name: PORT
          value: "3344"
        readinessProbe:
          httpGet:
            path: /health
            port: http-ws
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http-ws
          initialDelaySeconds: 5
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
