apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- deployment.yaml
- service.yaml
- route.yaml

labels:
- pairs:
    app.kubernetes.io/component: visualization
  includeSelectors: false
