apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- evaluator-job.yaml
- reward-model-job.yaml

labels:
- pairs:
    app.kubernetes.io/component: evaluator
  includeSelectors: false
