apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/operators
- ../base/llm-d-gateway

labels:
- pairs:
    app.kubernetes.io/part-of: zelda-rl
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false
