apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- hardware-profiles.yaml

labels:
- pairs:
    app.kubernetes.io/component: llm-d-gateway
  includeSelectors: false
