apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- gateway.yaml
- inference-pool-vision.yaml
- inference-pool-puzzle.yaml
- inference-pool-text.yaml
- httproute-vision.yaml
- httproute-dialog.yaml
- httproute-puzzle.yaml
- httproute-state.yaml
- epp-deployment.yaml
- epp-service.yaml

labels:
- pairs:
    app.kubernetes.io/component: llm-d-gateway
  includeSelectors: false
