apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- secret.yaml
- llm-inference-text.yaml
- llm-inference-puzzle.yaml
- llm-inference-vision.yaml

labels:
- pairs:
    app.kubernetes.io/component: llm-inference
  includeSelectors: false
