apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- serviceaccount.yaml
- rbac.yaml
- secret.yaml
- service.yaml
- inferenceservice-vision.yaml
- inferenceservice-puzzle.yaml
- inferenceservice-text.yaml

labels:
- pairs:
    app.kubernetes.io/component: llm-inference
  includeSelectors: false
