apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- servicemonitor.yaml
- grafana-dashboard-cm.yaml

labels:
- pairs:
    app.kubernetes.io/component: monitoring
  includeSelectors: false
