apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zelda-rl

resources:
- serviceaccount.yaml
- rbac.yaml
- raycluster.yaml
- rayjob.yaml
- kueue-localqueue.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/component: rl-training
  includeSelectors: false
